steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/jmc-devsecops/artifact-scanning-repo/cymbal-eats-fe', './cymbal-eats-fe']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-south1-docker.pkg.dev/jmc-devsecops/artifact-scanning-repo/cymbal-eats-fe' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'cymbal-eats-fe'
    - '--image'
    - 'asia-south1-docker.pkg.dev/jmc-devsecops/artifact-scanning-repo/cymbal-eats-fe'
    - '--region'
    - 'us-central1'
    - '--concurrency'
    - '80'
    - '--max-instances'
    - '3'
    - '--min-instances'
    - '0'
    - '--timeout'
    - '300'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT=cloud-next25-screendemo'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'services'
    - 'add-iam-policy-binding'
    - 'cymbal-eats-fe'
    - '--region'
    - 'us-central1'
    - '--member'
    - 'allUsers'
    - '--role'
    - 'roles/run.invoker'
images:
- 'us-central1-docker.pkg.dev/cloud-next25-screendemo/cloud-next25-screendemo/cymbal-eats-fe'
options:
    logging: CLOUD_LOGGING_ONLY
